src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EntrepriseRepository::class)
 */
class Entreprise
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $raisonSociale;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Employe::class, mappedBy="entreprise", orphanRemoval=true)
     */
    private $employes;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $siret;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): self
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getFullAdresse() 
    {
        return $this->adresse." ".$this->cp." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->employes->contains($employe)) {
            $this->employes[] = $employe;
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->raisonSociale." (".$this->cp." ".$this->ville.")";
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // informe que le champs sera un input de type text
            ->add('raisonSociale', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('dateCreation', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control']
            ])
            ->add('adresse', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('cp', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('ville', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('siret', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'btn btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    /**
     * @Route("/entreprise", name="app_entreprise")
     */
    // public function index(ManagerRegistry $doctrine): Response
    // {
    //     // test en ajoutant un tableau
    //     // $tableau = ["valeur 1","valeur 2","valeur 3","valeur 4","valeur 5"];

    //     // fonction qui récupère les entreprises dans la BDO
    //     // https://symfony.com/doc/current/doctrine.html#fetching-objects-from-the-database
    //     $entreprises = $doctrine->getRepository(Entreprise::class)->findAll();
    //     return $this->render('entreprise/index.html.twig', [
    //         'entreprises' => $entreprises

    //         // test en ajoutant à name, une valeur (ici -> Mickael)
    //         // 'name'=>'Mickael',
    //         // 'tableau' => $tableau
    //     ]);


    public function index(ManagerRegistry $doctrine): Response
    {
        $entreprises = $doctrine->getRepository(Entreprise::class)->findBy([], ["raisonSociale" => "DESC"]);
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises
        ]);
    }

    // ADD FORMULAIRE (mettre avant les recherches en détails -> risque de confusion)
    // bien mettre l'id dans la route si on veux cibler une donnée
    /**
     * @Route("/entreprise/add", name="add_entreprise")
     * @Route("/entreprise/{id}/edit", name="edit_entreprise")
     */
    public function add(ManagerRegistry $doctrine, Entreprise $entreprise = null, Request $request): Response {

        if(!$entreprise) {
            $entreprise = new Entreprise();
        }


        // construit un formulaire à partir d'un builder (EntrepriseType)
        $form = $this->createForm(EntrepriseType::class, $entreprise);
        // récupère les données de l'objet pour les envoyer dans le formulaire
        $form->handleRequest($request);

        // si le formulaire est soumis et que les filtes ont été validés (fonctions natives de symfony)
        if($form->isSubmitted() && $form->isValid()) {

            $entreprise = $form->getData();
            // recupère depuis doctrine, le manager qui est initialisé (où se situe le persist et le flush)
            $entityManager = $doctrine->getManager();
            // équivalent tu prepare();
            $entityManager->persist($entreprise);
            // équivalent du execute() -> insert into
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        // vue pour afficher le formulaire d'ajout
        return $this->render('entreprise/add.html.twig', [
            // création d'une variable qui fait passer le formulaire qui a était créé visuellement
            'formAddEntreprise' => $form->createView(),
            'edit' => $entreprise->getId()
        ]);
    }

    // SUPPRESSION ENTREPRISE + EMPLOYE LIE
    /**
     * @Route("entreprise/{id}/delete", name="delete_entreprise")
     */
    public function delete(ManagerRegistry $doctrine, Entreprise $entreprise) {

        $entityManager = $doctrine->getManager();
        // enleve de la collection de la base de données
        $entityManager->remove($entreprise);
        $entityManager->flush();

        return $this->redirectToRoute('app_entreprise');
    }

    // ACTION 
    /**
     * @Route("/entreprise/{id}", name="show_entreprise")
     */
    public function show(Entreprise $entreprise): Response 
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise
        ]);
    }

}

templates/entreprise/add.html.twig
{# heritage de la vue mais pas dans le sens de la POO #}
{% extends 'base.html.twig' %}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}

    {% if edit %}
        <h1>Editer une entreprise</h1>
    {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}
    
    {# fonction de twig #}
    {# {{ form(formAddEntreprise) }} #}

    {{ form_start(formAddEntreprise) }}
    {# BUG #}
        <div>
            {{ form_row(formAddEntreprise.raisonSociale) }}
            {{ form_row(formAddEntreprise.dateCreation) }}
            {{ form_row(formAddEntreprise.siret) }}
        </div>
        <div>
            {{ form_row(formAddEntreprise.adresse) }}
            {{ form_row(formAddEntreprise.cp) }}
            {{ form_row(formAddEntreprise.ville) }}
        </div>
        <div>
            {{ form_row(formAddEntreprise.submit) }}        
        </div>      
    {{ form_end(formAddEntreprise) }}
    
{% endblock %}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}
    <h1>Liste des entreprises</h1>

    <a class="btn btn-primary"  href="{{ path('add_entreprise') }}">Ajouter une entreprise</a><br>


    {# vardump sur symfony #}
    {# {{ dump(entreprises)}} #}

    {# <p>lorem</p> #}
{# {{}} : équivalent du echo dans PHP #}
{# permet d'appeler les données insérées dans le controlleur (EntrepriseController) #}
    {# <p>Hello {{ name }} </p> #}

{# donne un nom au for -> (ici "element") #}
    {# {% for element in tableau %} #}
        {# {{ element }} <br> #}
    {# {% endfor %}  #}

    {% for entreprise in entreprises %}
    {# appelle la variable entreprise avec un getsous la forme xx.xx #}
        {# {{ entreprise.raisonSociale ~ ' ( ' ~ entreprise.cp ~ ' ' ~ entreprise.ville ~ ')'  }} #}
        <br>
        {# autre façon de l'écrire #}
        {# {{ entreprise.raisonSociale }} ({{entreprise.cp}} {{entreprise.ville}}) <br> #}
    
        {# si il y a un tostring, on peux l'appeler comme ceci #}
        <a href="{{ path('show_entreprise', {'id': entreprise.id}) }}">{{ entreprise }}</a> <br>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id': entreprise.id}) }}">Editer</a> <br>
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id': entreprise.id}) }}">Supprimer</a> <br>
    {% endfor %}

{% endblock %}

templates/entreprise/show.html.twig
{# heritage de la vue mais pas dans le sens de la POO #}
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}

    <h1>{{ entreprise }}</h1>
 
    

    <p>
        SIRET:  {{ entreprise.siret }}<br>
        Date de création: {{ entreprise.dateCreation | date('d-m-Y') }} <br>
        Adresse: {{ entreprise.fullAdresse }}
    </p>

    <h2>Liste des employés</h2>

        {% if entreprise.employes | length == 0 %}

        <p>pas d'employé dans l'entreprise</p>

        {% else %}
        
            {% for employe in entreprise.employes %}
               <a href="{{ path('show_employe', {'id':employe.id}) }}">{{employe}}</a>  <br>
            {% endfor %}

        {% endif %}

{% endblock %}