src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 */
class Employe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEmbauche;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    // FONCTION AJOUTEE MANUELLEMENT
    public function getAge()
    {
        $now = new \Datetime();
        $interval = date_diff($this->dateNaissance, $now);
        return $interval->format("%Y");
    }

    public function __toString()
    {
    // "$this->getEntreprise()" fonctionne que si il y a un __toString dans l'entité Entreprise
    // return $this->prenom." ".$this->nom." (".$this->getEntreprise().")";
        return $this->prenom." ".$this->nom;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('prenom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control']
            ])
            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control']
            ])
            ->add('ville', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('entreprise', EntityType::class, [
                //relie à l'entité entreprise
                'class' => Entreprise::class,
                //selectionne le label a afficher
                'choice_label' => 'raisonSociale',
                'attr' => ['class' => 'form-control']
            ])
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'btn btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    /**
     * @Route("/employe", name="app_employe")
     */
    // VERSION FINDALL identique à FINDBY mais on ne peux pas trier par ordre croissant ou décroissant
    // réponse HTTP -> response
    public function index(ManagerRegistry $doctrine): Response
    {
        $employes = $doctrine->getRepository(Employe::class)->findAll();
        return $this->render('employe/index.html.twig', [
            'employes' => $employes
        ]);
    }

    // FONCTION QUI TRIE ORDRE CROISSANT NOM ET SEULEMENT CEUX DONT VILLE EST STRASBOURG
    // public function index(ManagerRegistry $doctrine): Response
    // {
    //     $employes = $doctrine->getRepository(Employe::class)->findBy(["ville" =>"Strasbourg"], ["nom" => "ASC"]);
    //     return $this->render('employe/index.html.twig', [
    //         'employes' => $employes
    //     ]);
    // }


    // ADD FORMULAIRE (mettre avant les recherches en détails -> risque de confusion)
    /**
     * @Route("/employe/add", name="add_employe")
     * @Route("/employe/{id}/edit", name="edit_employe")
     */
    public function add(ManagerRegistry $doctrine, Employe $employe = null, Request $request): Response {

        if(!$employe) {
            $employe= new Employe();
        }

        // construit un formulaire à partir d'un builder (EmployeType)
        $form = $this->createForm(EmployeType::class, $employe);
        // récupère les données de l'objet pour les envoyer dans le formulaire
        $form->handleRequest($request);

        // si le formulaire est soumis et que les filtes ont été validés (fonctions natives de symfony)
        if($form->isSubmitted() && $form->isValid()) {

            $employe = $form->getData();
            // recupère depuis doctrine, le manager qui est initialisé (où se situe le persist et le flush)
            $entityManager = $doctrine->getManager();
            // équivalent tu prepare();
            $entityManager->persist($employe);
            // équivalent du execute() -> insert into
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }

        // vue pour afficher le formulaire d'ajout
        return $this->render('employe/add.html.twig', [
            // création d'une variable qui fait passer le formulaire qui a était créé visuellement
            'formAddEmploye' => $form->createView(),
            'edit' => $employe->getId()
        ]);
    }

    // SUPPRESSION EMPLOYE
    /**
     * @Route("employe/{id}/delete", name="delete_employe")
     */
    public function delete(ManagerRegistry $doctrine, Employe $employe) {

        $entityManager = $doctrine->getManager();
        // enleve de la collection de la base de données
        $entityManager->remove($employe);
        $entityManager->flush();

        return $this->redirectToRoute('app_employe');
    }

    // RESPECTER LA SYNTAXE PRECISE DE LA ROUTE !
    /**
     * @Route("/employe/{id}", name="show_employe")
     */
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe
        ]);
    }
}

templates/employe/add.html.twig
{# heritage de la vue mais pas dans le sens de la POO #}
{% extends 'base.html.twig' %}

{% block title %}Ajouter un employé{% endblock %}

{% block body %}

    {# BUG #}
    {% if edit %}
        <h1>Editer un employé</h1>
    {% else %}
        <h1>Ajouter un employé</h1>
    {% endif %}
        
    {# <h1>Ajouter un employé</h1> #}

    {# personnaliser son formulaire #}
    {{ form_start(formAddEmploye) }}

    {# BUG #}
        <div class="prenomNom">
            {{ form_row(formAddEmploye.prenom) }}
            {{ form_row(formAddEmploye.nom) }}
        </div>
        <div>
            {{ form_row(formAddEmploye.dateNaissance) }}
            {{ form_row(formAddEmploye.dateEmbauche) }}
            {{ form_row(formAddEmploye.ville) }}
            {{ form_row(formAddEmploye.entreprise) }}
            {{ form_row(formAddEmploye.submit) }}
        </div>
        
    {{ form_end(formAddEmploye) }}

    {# fonction de twig #}
    {# {{ form(formAddEmploye) }} #}


{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}
    <h1>Liste des employés</h1>

    <a class="btn btn-primary"  href="{{ path('add_employe') }}">Ajouter un employe</a><br>


    {% for employe in employes %}
        <a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }}</a> <br>
        <a class="btn btn-warning" href="{{ path('edit_employe', {'id': employe.id}) }}">Editer</a> <br>
        <a class="btn btn-danger" href="{{ path('delete_employe', {'id': employe.id}) }}">Supprimer</a> <br>

    {% endfor %}
{% endblock %}

templates/employe/show.html.twig
{# heritage de la vue mais pas dans le sens de la POO #}
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}

    <h1>{{ employe }}</h1>
 
    

    <p>
        Ville: {{ employe.ville }} <br>
        Entreprise: <a href="{{ path('show_entreprise', {'id':employe.entreprise.id}) }}">{{ employe.entreprise.raisonSociale }}</a>   <br>
        Date d'embauche: {{ employe.dateEmbauche | date('d/m/Y') }} <br>
        Date de naissance: {{ employe.dateNaissance | date('d/m/Y') }} ({{ employe.age }} ans)

    </p>
{% endblock %}